import { Button, VerticalBox, CheckBox, GroupBox } from "std-widgets.slint";

export struct Task {
    id: string,
    completed: bool,
    description: string,
}

export component AppWindow inherits Window {
    in-out property <[Task]> task-list;
    callback request-mark-task(string);
    GroupBox {
        VerticalLayout {
            for data in root.task-list: my-repeated-text := CheckBox {
                toggled => {
                    root.request-mark-task(data.id);
                }
                opacity: 0.7;
                checked: data.completed;
                text: data.description;
            }
        }
    }
}
